name: Install Pipenv Dependencies
description: Github Action for installing pipenv dependencies

runs:
  using: composite
  steps:
    - name: Setup ssh key for git
      shell: bash
      run: |
        mkdir -p /home/runner/.ssh
        ssh-keyscan -t rsa github.com > /home/runner/.ssh/known_hosts
        echo "$SSH_KEY" > /home/runner/.ssh/id_rsa
        chmod 400 /home/runner/.ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
