name: Install Pipenv Dependencies
description: Github Action for installing pipenv dependencies

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.0'
        cache: pipenv

    - id: cache-pipenv
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies (pipenv)
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pipenv install --deploy --dev
